window.WC = {
 "champion": {
  "rank": 1,
  "team": "Spain",
  "champ": 22.1,
  "final": 33.2,
  "semi": 46.4
 },
 "titleRace": [
  {
   "rank": 1,
   "team": "Spain",
   "champ": 22.1,
   "final": 33.2,
   "semi": 46.4
  },
  {
   "rank": 2,
   "team": "Argentina",
   "champ": 15.7,
   "final": 25.9,
   "semi": 38.6
  },
  {
   "rank": 3,
   "team": "France",
   "champ": 10.6,
   "final": 18.9,
   "semi": 34.0
  },
  {
   "rank": 4,
   "team": "England",
   "champ": 7.1,
   "final": 13.9,
   "semi": 25.7
  },
  {
   "rank": 5,
   "team": "Brazil",
   "champ": 5.1,
   "final": 10.3,
   "semi": 20.9
  },
  {
   "rank": 6,
   "team": "Portugal",
   "champ": 4.9,
   "final": 10.4,
   "semi": 19.2
  },
  {
   "rank": 7,
   "team": "Colombia",
   "champ": 4.8,
   "final": 10.0,
   "semi": 18.5
  },
  {
   "rank": 8,
   "team": "Netherlands",
   "champ": 3.3,
   "final": 7.4,
   "semi": 16.7
  }
 ],
 "scorers": [
  {
   "rank": 1,
   "player": "Kylian Mbappé",
   "team": "France",
   "goals": 7.0,
   "share": 46
  },
  {
   "rank": 2,
   "player": "Lamine Yamal",
   "team": "Spain",
   "goals": 6.9,
   "share": 34
  },
  {
   "rank": 3,
   "player": "Lautaro Martínez",
   "team": "Argentina",
   "goals": 6.5,
   "share": 38
  },
  {
   "rank": 4,
   "player": "Harry Kane",
   "team": "England",
   "goals": 6.4,
   "share": 44
  },
  {
   "rank": 5,
   "player": "Erling Haaland",
   "team": "Norway",
   "goals": 5.0,
   "share": 56
  },
  {
   "rank": 6,
   "player": "Enner Valencia",
   "team": "Ecuador",
   "goals": 5.0,
   "share": 42
  }
 ],
 "groups": {
  "A": {
   "standings": [
    {
     "team": "Mexico",
     "p": 3,
     "w": 3,
     "d": 0,
     "l": 0,
     "gf": 7,
     "ga": 3,
     "pts": 9,
     "gd": 4,
     "padv": 98,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "South Korea",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 78,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Czechia",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 74,
     "pos": 3,
     "result": "Q3"
    },
    {
     "team": "South Africa",
     "p": 3,
     "w": 0,
     "d": 0,
     "l": 3,
     "gf": 3,
     "ga": 7,
     "pts": 0,
     "gd": -4,
     "padv": 20,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-11",
     "home": "Mexico",
     "away": "South Africa",
     "hs": 3,
     "as_": 1,
     "wp": 84,
     "dp": 11,
     "lp": 4,
     "xgh": 2.8,
     "xga": 0.5
    },
    {
     "md": 1,
     "date": "06-11",
     "home": "South Korea",
     "away": "Czechia",
     "hs": 1,
     "as_": 1,
     "wp": 38,
     "dp": 27,
     "lp": 34,
     "xgh": 1.3,
     "xga": 1.2
    },
    {
     "md": 2,
     "date": "06-18",
     "home": "Czechia",
     "away": "South Africa",
     "hs": 2,
     "as_": 1,
     "wp": 63,
     "dp": 21,
     "lp": 16,
     "xgh": 2.0,
     "xga": 0.9
    },
    {
     "md": 2,
     "date": "06-18",
     "home": "Mexico",
     "away": "South Korea",
     "hs": 2,
     "as_": 1,
     "wp": 63,
     "dp": 21,
     "lp": 16,
     "xgh": 2.0,
     "xga": 0.9
    },
    {
     "md": 3,
     "date": "06-24",
     "home": "Mexico",
     "away": "Czechia",
     "hs": 2,
     "as_": 1,
     "wp": 65,
     "dp": 20,
     "lp": 15,
     "xgh": 2.0,
     "xga": 0.8
    },
    {
     "md": 3,
     "date": "06-24",
     "home": "South Africa",
     "away": "South Korea",
     "hs": 1,
     "as_": 2,
     "wp": 15,
     "dp": 20,
     "lp": 65,
     "xgh": 0.8,
     "xga": 2.0
    }
   ]
  },
  "B": {
   "standings": [
    {
     "team": "Switzerland",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "gf": 6,
     "ga": 2,
     "pts": 7,
     "gd": 4,
     "padv": 97,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Canada",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "gf": 6,
     "ga": 2,
     "pts": 7,
     "gd": 4,
     "padv": 97,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Bosnia",
     "p": 3,
     "w": 1,
     "d": 0,
     "l": 2,
     "gf": 4,
     "ga": 5,
     "pts": 3,
     "gd": -1,
     "padv": 54,
     "pos": 3,
     "result": "Q3"
    },
    {
     "team": "Qatar",
     "p": 3,
     "w": 0,
     "d": 0,
     "l": 3,
     "gf": 1,
     "ga": 8,
     "pts": 0,
     "gd": -7,
     "padv": 14,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-12",
     "home": "Canada",
     "away": "Bosnia",
     "hs": 2,
     "as_": 1,
     "wp": 71,
     "dp": 18,
     "lp": 11,
     "xgh": 2.2,
     "xga": 0.8
    },
    {
     "md": 2,
     "date": "06-13",
     "home": "Qatar",
     "away": "Switzerland",
     "hs": 0,
     "as_": 3,
     "wp": 4,
     "dp": 11,
     "lp": 85,
     "xgh": 0.5,
     "xga": 2.8
    },
    {
     "md": 3,
     "date": "06-18",
     "home": "Switzerland",
     "away": "Bosnia",
     "hs": 2,
     "as_": 1,
     "wp": 71,
     "dp": 18,
     "lp": 11,
     "xgh": 2.2,
     "xga": 0.8
    },
    {
     "md": 3,
     "date": "06-18",
     "home": "Canada",
     "away": "Qatar",
     "hs": 3,
     "as_": 0,
     "wp": 85,
     "dp": 11,
     "lp": 4,
     "xgh": 2.8,
     "xga": 0.5
    },
    {
     "md": 4,
     "date": "06-24",
     "home": "Canada",
     "away": "Switzerland",
     "hs": 1,
     "as_": 1,
     "wp": 36,
     "dp": 28,
     "lp": 37,
     "xgh": 1.2,
     "xga": 1.2
    },
    {
     "md": 4,
     "date": "06-24",
     "home": "Bosnia",
     "away": "Qatar",
     "hs": 2,
     "as_": 1,
     "wp": 58,
     "dp": 23,
     "lp": 19,
     "xgh": 1.8,
     "xga": 0.9
    }
   ]
  },
  "C": {
   "standings": [
    {
     "team": "Brazil",
     "p": 3,
     "w": 3,
     "d": 0,
     "l": 0,
     "gf": 7,
     "ga": 3,
     "pts": 9,
     "gd": 4,
     "padv": 97,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Morocco",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 83,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Scotland",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 74,
     "pos": 3,
     "result": "Q3"
    },
    {
     "team": "Haiti",
     "p": 3,
     "w": 0,
     "d": 0,
     "l": 3,
     "gf": 3,
     "ga": 7,
     "pts": 0,
     "gd": -4,
     "padv": 18,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-13",
     "home": "Brazil",
     "away": "Morocco",
     "hs": 2,
     "as_": 1,
     "wp": 57,
     "dp": 23,
     "lp": 20,
     "xgh": 1.8,
     "xga": 1.0
    },
    {
     "md": 1,
     "date": "06-13",
     "home": "Haiti",
     "away": "Scotland",
     "hs": 1,
     "as_": 2,
     "wp": 15,
     "dp": 20,
     "lp": 65,
     "xgh": 0.8,
     "xga": 2.0
    },
    {
     "md": 2,
     "date": "06-19",
     "home": "Scotland",
     "away": "Morocco",
     "hs": 1,
     "as_": 1,
     "wp": 31,
     "dp": 27,
     "lp": 42,
     "xgh": 1.1,
     "xga": 1.4
    },
    {
     "md": 2,
     "date": "06-19",
     "home": "Brazil",
     "away": "Haiti",
     "hs": 3,
     "as_": 1,
     "wp": 83,
     "dp": 12,
     "lp": 5,
     "xgh": 2.8,
     "xga": 0.5
    },
    {
     "md": 3,
     "date": "06-24",
     "home": "Scotland",
     "away": "Brazil",
     "hs": 1,
     "as_": 2,
     "wp": 17,
     "dp": 22,
     "lp": 62,
     "xgh": 0.9,
     "xga": 1.9
    },
    {
     "md": 3,
     "date": "06-24",
     "home": "Morocco",
     "away": "Haiti",
     "hs": 2,
     "as_": 1,
     "wp": 69,
     "dp": 19,
     "lp": 12,
     "xgh": 2.2,
     "xga": 0.8
    }
   ]
  },
  "D": {
   "standings": [
    {
     "team": "Turkiye",
     "p": 3,
     "w": 1,
     "d": 2,
     "l": 0,
     "gf": 4,
     "ga": 3,
     "pts": 5,
     "gd": 1,
     "padv": 84,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Paraguay",
     "p": 3,
     "w": 0,
     "d": 3,
     "l": 0,
     "gf": 3,
     "ga": 3,
     "pts": 3,
     "gd": 0,
     "padv": 69,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "USA",
     "p": 3,
     "w": 0,
     "d": 3,
     "l": 0,
     "gf": 3,
     "ga": 3,
     "pts": 3,
     "gd": 0,
     "padv": 67,
     "pos": 3,
     "result": "Q3"
    },
    {
     "team": "Australia",
     "p": 3,
     "w": 0,
     "d": 2,
     "l": 1,
     "gf": 3,
     "ga": 4,
     "pts": 2,
     "gd": -1,
     "padv": 55,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-12",
     "home": "USA",
     "away": "Paraguay",
     "hs": 1,
     "as_": 1,
     "wp": 35,
     "dp": 28,
     "lp": 37,
     "xgh": 1.2,
     "xga": 1.2
    },
    {
     "md": 2,
     "date": "06-13",
     "home": "Australia",
     "away": "Turkiye",
     "hs": 1,
     "as_": 2,
     "wp": 23,
     "dp": 24,
     "lp": 53,
     "xgh": 1.0,
     "xga": 1.7
    },
    {
     "md": 3,
     "date": "06-19",
     "home": "USA",
     "away": "Australia",
     "hs": 1,
     "as_": 1,
     "wp": 42,
     "dp": 27,
     "lp": 31,
     "xgh": 1.4,
     "xga": 1.1
    },
    {
     "md": 3,
     "date": "06-19",
     "home": "Turkiye",
     "away": "Paraguay",
     "hs": 1,
     "as_": 1,
     "wp": 46,
     "dp": 26,
     "lp": 28,
     "xgh": 1.5,
     "xga": 1.1
    },
    {
     "md": 4,
     "date": "06-25",
     "home": "USA",
     "away": "Turkiye",
     "hs": 1,
     "as_": 1,
     "wp": 27,
     "dp": 26,
     "lp": 47,
     "xgh": 1.1,
     "xga": 1.5
    },
    {
     "md": 4,
     "date": "06-25",
     "home": "Paraguay",
     "away": "Australia",
     "hs": 1,
     "as_": 1,
     "wp": 43,
     "dp": 27,
     "lp": 30,
     "xgh": 1.4,
     "xga": 1.1
    }
   ]
  },
  "E": {
   "standings": [
    {
     "team": "Ecuador",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "gf": 6,
     "ga": 2,
     "pts": 7,
     "gd": 4,
     "padv": 97,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Germany",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "gf": 6,
     "ga": 2,
     "pts": 7,
     "gd": 4,
     "padv": 97,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Ivory Coast",
     "p": 3,
     "w": 1,
     "d": 0,
     "l": 2,
     "gf": 4,
     "ga": 5,
     "pts": 3,
     "gd": -1,
     "padv": 66,
     "pos": 3,
     "result": "Q3"
    },
    {
     "team": "Curacao",
     "p": 3,
     "w": 0,
     "d": 0,
     "l": 3,
     "gf": 1,
     "ga": 8,
     "pts": 0,
     "gd": -7,
     "padv": 9,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-14",
     "home": "Germany",
     "away": "Curacao",
     "hs": 3,
     "as_": 0,
     "wp": 87,
     "dp": 10,
     "lp": 3,
     "xgh": 2.9,
     "xga": 0.5
    },
    {
     "md": 1,
     "date": "06-14",
     "home": "Ivory Coast",
     "away": "Ecuador",
     "hs": 1,
     "as_": 2,
     "wp": 14,
     "dp": 20,
     "lp": 66,
     "xgh": 0.8,
     "xga": 2.1
    },
    {
     "md": 2,
     "date": "06-20",
     "home": "Germany",
     "away": "Ivory Coast",
     "hs": 2,
     "as_": 1,
     "wp": 65,
     "dp": 20,
     "lp": 15,
     "xgh": 2.0,
     "xga": 0.8
    },
    {
     "md": 2,
     "date": "06-20",
     "home": "Ecuador",
     "away": "Curacao",
     "hs": 3,
     "as_": 0,
     "wp": 87,
     "dp": 9,
     "lp": 3,
     "xgh": 3.0,
     "xga": 0.4
    },
    {
     "md": 3,
     "date": "06-25",
     "home": "Curacao",
     "away": "Ivory Coast",
     "hs": 1,
     "as_": 2,
     "wp": 13,
     "dp": 19,
     "lp": 67,
     "xgh": 0.8,
     "xga": 2.1
    },
    {
     "md": 3,
     "date": "06-25",
     "home": "Ecuador",
     "away": "Germany",
     "hs": 1,
     "as_": 1,
     "wp": 37,
     "dp": 28,
     "lp": 35,
     "xgh": 1.2,
     "xga": 1.2
    }
   ]
  },
  "F": {
   "standings": [
    {
     "team": "Netherlands",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "gf": 5,
     "ga": 3,
     "pts": 7,
     "gd": 2,
     "padv": 94,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Japan",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "gf": 5,
     "ga": 3,
     "pts": 7,
     "gd": 2,
     "padv": 90,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Sweden",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "gf": 3,
     "ga": 5,
     "pts": 1,
     "gd": -2,
     "padv": 54,
     "pos": 3,
     "result": "OUT"
    },
    {
     "team": "Tunisia",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "gf": 3,
     "ga": 5,
     "pts": 1,
     "gd": -2,
     "padv": 31,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-14",
     "home": "Netherlands",
     "away": "Japan",
     "hs": 1,
     "as_": 1,
     "wp": 42,
     "dp": 27,
     "lp": 32,
     "xgh": 1.3,
     "xga": 1.1
    },
    {
     "md": 1,
     "date": "06-14",
     "home": "Sweden",
     "away": "Tunisia",
     "hs": 1,
     "as_": 1,
     "wp": 47,
     "dp": 26,
     "lp": 27,
     "xgh": 1.5,
     "xga": 1.1
    },
    {
     "md": 2,
     "date": "06-20",
     "home": "Netherlands",
     "away": "Sweden",
     "hs": 2,
     "as_": 1,
     "wp": 65,
     "dp": 20,
     "lp": 15,
     "xgh": 2.0,
     "xga": 0.8
    },
    {
     "md": 2,
     "date": "06-20",
     "home": "Tunisia",
     "away": "Japan",
     "hs": 1,
     "as_": 2,
     "wp": 12,
     "dp": 19,
     "lp": 69,
     "xgh": 0.8,
     "xga": 2.2
    },
    {
     "md": 3,
     "date": "06-25",
     "home": "Japan",
     "away": "Sweden",
     "hs": 2,
     "as_": 1,
     "wp": 60,
     "dp": 22,
     "lp": 18,
     "xgh": 1.9,
     "xga": 0.9
    },
    {
     "md": 3,
     "date": "06-25",
     "home": "Tunisia",
     "away": "Netherlands",
     "hs": 1,
     "as_": 2,
     "wp": 10,
     "dp": 17,
     "lp": 73,
     "xgh": 0.7,
     "xga": 2.3
    }
   ]
  },
  "G": {
   "standings": [
    {
     "team": "Belgium",
     "p": 3,
     "w": 3,
     "d": 0,
     "l": 0,
     "gf": 6,
     "ga": 3,
     "pts": 9,
     "gd": 3,
     "padv": 94,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Iran",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 81,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Egypt",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 66,
     "pos": 3,
     "result": "Q3"
    },
    {
     "team": "New Zealand",
     "p": 3,
     "w": 0,
     "d": 0,
     "l": 3,
     "gf": 3,
     "ga": 6,
     "pts": 0,
     "gd": -3,
     "padv": 30,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-15",
     "home": "Belgium",
     "away": "Egypt",
     "hs": 2,
     "as_": 1,
     "wp": 61,
     "dp": 22,
     "lp": 18,
     "xgh": 1.9,
     "xga": 0.9
    },
    {
     "md": 1,
     "date": "06-15",
     "home": "Iran",
     "away": "New Zealand",
     "hs": 2,
     "as_": 1,
     "wp": 62,
     "dp": 21,
     "lp": 17,
     "xgh": 1.9,
     "xga": 0.9
    },
    {
     "md": 2,
     "date": "06-21",
     "home": "Belgium",
     "away": "Iran",
     "hs": 2,
     "as_": 1,
     "wp": 51,
     "dp": 25,
     "lp": 24,
     "xgh": 1.6,
     "xga": 1.0
    },
    {
     "md": 2,
     "date": "06-21",
     "home": "New Zealand",
     "away": "Egypt",
     "hs": 1,
     "as_": 2,
     "wp": 23,
     "dp": 24,
     "lp": 53,
     "xgh": 1.0,
     "xga": 1.7
    },
    {
     "md": 3,
     "date": "06-26",
     "home": "Egypt",
     "away": "Iran",
     "hs": 1,
     "as_": 1,
     "wp": 28,
     "dp": 26,
     "lp": 46,
     "xgh": 1.1,
     "xga": 1.5
    },
    {
     "md": 3,
     "date": "06-26",
     "home": "New Zealand",
     "away": "Belgium",
     "hs": 1,
     "as_": 2,
     "wp": 9,
     "dp": 16,
     "lp": 74,
     "xgh": 0.7,
     "xga": 2.4
    }
   ]
  },
  "H": {
   "standings": [
    {
     "team": "Spain",
     "p": 3,
     "w": 3,
     "d": 0,
     "l": 0,
     "gf": 8,
     "ga": 1,
     "pts": 9,
     "gd": 7,
     "padv": 100,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Uruguay",
     "p": 3,
     "w": 2,
     "d": 0,
     "l": 1,
     "gf": 5,
     "ga": 4,
     "pts": 6,
     "gd": 1,
     "padv": 92,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Cape Verde",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "gf": 2,
     "ga": 6,
     "pts": 1,
     "gd": -4,
     "padv": 28,
     "pos": 3,
     "result": "OUT"
    },
    {
     "team": "Saudi Arabia",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "gf": 2,
     "ga": 6,
     "pts": 1,
     "gd": -4,
     "padv": 26,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-15",
     "home": "Spain",
     "away": "Cape Verde",
     "hs": 3,
     "as_": 0,
     "wp": 91,
     "dp": 7,
     "lp": 2,
     "xgh": 3.2,
     "xga": 0.3
    },
    {
     "md": 1,
     "date": "06-15",
     "home": "Saudi Arabia",
     "away": "Uruguay",
     "hs": 1,
     "as_": 2,
     "wp": 10,
     "dp": 17,
     "lp": 74,
     "xgh": 0.7,
     "xga": 2.3
    },
    {
     "md": 2,
     "date": "06-21",
     "home": "Spain",
     "away": "Saudi Arabia",
     "hs": 3,
     "as_": 0,
     "wp": 92,
     "dp": 7,
     "lp": 2,
     "xgh": 3.3,
     "xga": 0.3
    },
    {
     "md": 2,
     "date": "06-21",
     "home": "Uruguay",
     "away": "Cape Verde",
     "hs": 2,
     "as_": 1,
     "wp": 73,
     "dp": 17,
     "lp": 10,
     "xgh": 2.3,
     "xga": 0.7
    },
    {
     "md": 3,
     "date": "06-26",
     "home": "Cape Verde",
     "away": "Saudi Arabia",
     "hs": 1,
     "as_": 1,
     "wp": 37,
     "dp": 28,
     "lp": 35,
     "xgh": 1.2,
     "xga": 1.2
    },
    {
     "md": 3,
     "date": "06-26",
     "home": "Uruguay",
     "away": "Spain",
     "hs": 1,
     "as_": 2,
     "wp": 13,
     "dp": 19,
     "lp": 68,
     "xgh": 0.8,
     "xga": 2.1
    }
   ]
  },
  "I": {
   "standings": [
    {
     "team": "France",
     "p": 3,
     "w": 3,
     "d": 0,
     "l": 0,
     "gf": 7,
     "ga": 3,
     "pts": 9,
     "gd": 4,
     "padv": 97,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Norway",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 84,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Senegal",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 76,
     "pos": 3,
     "result": "Q3"
    },
    {
     "team": "Iraq",
     "p": 3,
     "w": 0,
     "d": 0,
     "l": 3,
     "gf": 3,
     "ga": 7,
     "pts": 0,
     "gd": -4,
     "padv": 16,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-16",
     "home": "France",
     "away": "Senegal",
     "hs": 2,
     "as_": 1,
     "wp": 60,
     "dp": 22,
     "lp": 18,
     "xgh": 1.9,
     "xga": 0.9
    },
    {
     "md": 1,
     "date": "06-16",
     "home": "Iraq",
     "away": "Norway",
     "hs": 1,
     "as_": 2,
     "wp": 11,
     "dp": 18,
     "lp": 71,
     "xgh": 0.8,
     "xga": 2.2
    },
    {
     "md": 2,
     "date": "06-22",
     "home": "France",
     "away": "Iraq",
     "hs": 3,
     "as_": 1,
     "wp": 84,
     "dp": 12,
     "lp": 5,
     "xgh": 2.8,
     "xga": 0.5
    },
    {
     "md": 2,
     "date": "06-22",
     "home": "Norway",
     "away": "Senegal",
     "hs": 1,
     "as_": 1,
     "wp": 42,
     "dp": 27,
     "lp": 31,
     "xgh": 1.4,
     "xga": 1.1
    },
    {
     "md": 3,
     "date": "06-26",
     "home": "Norway",
     "away": "France",
     "hs": 1,
     "as_": 2,
     "wp": 21,
     "dp": 24,
     "lp": 55,
     "xgh": 1.0,
     "xga": 1.7
    },
    {
     "md": 3,
     "date": "06-26",
     "home": "Senegal",
     "away": "Iraq",
     "hs": 2,
     "as_": 1,
     "wp": 66,
     "dp": 20,
     "lp": 14,
     "xgh": 2.1,
     "xga": 0.8
    }
   ]
  },
  "J": {
   "standings": [
    {
     "team": "Argentina",
     "p": 3,
     "w": 3,
     "d": 0,
     "l": 0,
     "gf": 7,
     "ga": 3,
     "pts": 9,
     "gd": 4,
     "padv": 99,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Austria",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "gf": 4,
     "ga": 4,
     "pts": 4,
     "gd": 0,
     "padv": 73,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Algeria",
     "p": 3,
     "w": 0,
     "d": 2,
     "l": 1,
     "gf": 3,
     "ga": 4,
     "pts": 2,
     "gd": -1,
     "padv": 56,
     "pos": 3,
     "result": "OUT"
    },
    {
     "team": "Jordan",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "gf": 3,
     "ga": 6,
     "pts": 1,
     "gd": -3,
     "padv": 35,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-16",
     "home": "Argentina",
     "away": "Algeria",
     "hs": 2,
     "as_": 1,
     "wp": 76,
     "dp": 15,
     "lp": 8,
     "xgh": 2.4,
     "xga": 0.7
    },
    {
     "md": 1,
     "date": "06-16",
     "home": "Austria",
     "away": "Jordan",
     "hs": 2,
     "as_": 1,
     "wp": 55,
     "dp": 24,
     "lp": 21,
     "xgh": 1.7,
     "xga": 1.0
    },
    {
     "md": 2,
     "date": "06-22",
     "home": "Argentina",
     "away": "Austria",
     "hs": 2,
     "as_": 1,
     "wp": 70,
     "dp": 18,
     "lp": 12,
     "xgh": 2.2,
     "xga": 0.8
    },
    {
     "md": 2,
     "date": "06-22",
     "home": "Jordan",
     "away": "Algeria",
     "hs": 1,
     "as_": 1,
     "wp": 28,
     "dp": 26,
     "lp": 46,
     "xgh": 1.1,
     "xga": 1.5
    },
    {
     "md": 3,
     "date": "06-27",
     "home": "Algeria",
     "away": "Austria",
     "hs": 1,
     "as_": 1,
     "wp": 29,
     "dp": 26,
     "lp": 45,
     "xgh": 1.1,
     "xga": 1.4
    },
    {
     "md": 3,
     "date": "06-27",
     "home": "Jordan",
     "away": "Argentina",
     "hs": 1,
     "as_": 3,
     "wp": 5,
     "dp": 12,
     "lp": 83,
     "xgh": 0.5,
     "xga": 2.7
    }
   ]
  },
  "K": {
   "standings": [
    {
     "team": "Portugal",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "gf": 5,
     "ga": 3,
     "pts": 7,
     "gd": 2,
     "padv": 94,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Colombia",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "gf": 5,
     "ga": 3,
     "pts": 7,
     "gd": 2,
     "padv": 94,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Uzbekistan",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "gf": 3,
     "ga": 5,
     "pts": 1,
     "gd": -2,
     "padv": 46,
     "pos": 3,
     "result": "OUT"
    },
    {
     "team": "Congo DR",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "gf": 3,
     "ga": 5,
     "pts": 1,
     "gd": -2,
     "padv": 30,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-17",
     "home": "Portugal",
     "away": "Congo DR",
     "hs": 2,
     "as_": 1,
     "wp": 75,
     "dp": 16,
     "lp": 9,
     "xgh": 2.4,
     "xga": 0.7
    },
    {
     "md": 1,
     "date": "06-17",
     "home": "Uzbekistan",
     "away": "Colombia",
     "hs": 1,
     "as_": 2,
     "wp": 13,
     "dp": 19,
     "lp": 68,
     "xgh": 0.8,
     "xga": 2.1
    },
    {
     "md": 2,
     "date": "06-23",
     "home": "Portugal",
     "away": "Uzbekistan",
     "hs": 2,
     "as_": 1,
     "wp": 69,
     "dp": 19,
     "lp": 13,
     "xgh": 2.2,
     "xga": 0.8
    },
    {
     "md": 2,
     "date": "06-23",
     "home": "Colombia",
     "away": "Congo DR",
     "hs": 2,
     "as_": 1,
     "wp": 74,
     "dp": 16,
     "lp": 9,
     "xgh": 2.4,
     "xga": 0.7
    },
    {
     "md": 3,
     "date": "06-27",
     "home": "Colombia",
     "away": "Portugal",
     "hs": 1,
     "as_": 1,
     "wp": 36,
     "dp": 28,
     "lp": 37,
     "xgh": 1.2,
     "xga": 1.2
    },
    {
     "md": 3,
     "date": "06-27",
     "home": "Congo DR",
     "away": "Uzbekistan",
     "hs": 1,
     "as_": 1,
     "wp": 29,
     "dp": 26,
     "lp": 44,
     "xgh": 1.1,
     "xga": 1.4
    }
   ]
  },
  "L": {
   "standings": [
    {
     "team": "England",
     "p": 3,
     "w": 3,
     "d": 0,
     "l": 0,
     "gf": 7,
     "ga": 2,
     "pts": 9,
     "gd": 5,
     "padv": 98,
     "pos": 1,
     "result": "Q"
    },
    {
     "team": "Croatia",
     "p": 3,
     "w": 2,
     "d": 0,
     "l": 1,
     "gf": 6,
     "ga": 4,
     "pts": 6,
     "gd": 2,
     "padv": 93,
     "pos": 2,
     "result": "Q"
    },
    {
     "team": "Panama",
     "p": 3,
     "w": 1,
     "d": 0,
     "l": 2,
     "gf": 4,
     "ga": 5,
     "pts": 3,
     "gd": -1,
     "padv": 64,
     "pos": 3,
     "result": "Q3"
    },
    {
     "team": "Ghana",
     "p": 3,
     "w": 0,
     "d": 0,
     "l": 3,
     "gf": 2,
     "ga": 8,
     "pts": 0,
     "gd": -6,
     "padv": 13,
     "pos": 4,
     "result": "OUT"
    }
   ],
   "fixtures": [
    {
     "md": 1,
     "date": "06-17",
     "home": "England",
     "away": "Croatia",
     "hs": 2,
     "as_": 1,
     "wp": 50,
     "dp": 25,
     "lp": 25,
     "xgh": 1.6,
     "xga": 1.0
    },
    {
     "md": 1,
     "date": "06-17",
     "home": "Ghana",
     "away": "Panama",
     "hs": 1,
     "as_": 2,
     "wp": 16,
     "dp": 21,
     "lp": 63,
     "xgh": 0.9,
     "xga": 2.0
    },
    {
     "md": 2,
     "date": "06-23",
     "home": "England",
     "away": "Ghana",
     "hs": 3,
     "as_": 0,
     "wp": 88,
     "dp": 9,
     "lp": 3,
     "xgh": 3.0,
     "xga": 0.4
    },
    {
     "md": 2,
     "date": "06-23",
     "home": "Panama",
     "away": "Croatia",
     "hs": 1,
     "as_": 2,
     "wp": 19,
     "dp": 23,
     "lp": 59,
     "xgh": 0.9,
     "xga": 1.8
    },
    {
     "md": 3,
     "date": "06-27",
     "home": "Panama",
     "away": "England",
     "hs": 1,
     "as_": 2,
     "wp": 11,
     "dp": 18,
     "lp": 71,
     "xgh": 0.8,
     "xga": 2.2
    },
    {
     "md": 3,
     "date": "06-27",
     "home": "Croatia",
     "away": "Ghana",
     "hs": 3,
     "as_": 1,
     "wp": 80,
     "dp": 13,
     "lp": 6,
     "xgh": 2.6,
     "xga": 0.6
    }
   ]
  }
 },
 "meta": {
  "sims": 200000,
  "champSigma": 100,
  "draws": 18,
  "ngames": 72,
  "goalsPerGame": 2.82,
  "simDraw": 20,
  "simGoals": 2.86
 }
};
